name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name fastapi-container fastapi-app
        echo "Container is running. You can access the API at http://localhost:8000"
        docker ps
